# Generated by Django 6.0.1 on 2026-02-02 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MissingChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('last_seen_location', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='missing_children/')),
                ('embedding', models.BinaryField()),
                ('status', models.CharField(default='missing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='core.policestation')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=100)),
                ('reporter_phone', models.CharField(max_length=20)),
                ('found_location', models.CharField(max_length=250)),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='unmatched', max_length=20)),
                ('is_seen_by_station', models.BooleanField(default=False)),
                ('matched_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.missingchild')),
                ('matched_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.policestation')),
            ],
        ),
        migrations.CreateModel(
            name='StationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.policestation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
